sudo: required
dist: trusty
language: php
php:
  - "7.1"
  - "7.2"
  - "7.3"
services:
  - mysql
  - postgresql
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
  sonarcloud:
    organization: "autowp-github"
    token:
      secure: $SONARCLOUD_TOKEN
install:
  - pear config-set preferred_state beta
  - pecl channel-update pecl.php.net
  - yes | pecl install imagick
  
before_script: 
  - composer install --no-progress --no-interaction --no-suggest --ignore-platform-reqs
  - mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql
  - mysql -u root -e 'create database autowp_image_test;'
  - mysql -u root < test/_files/dump.mysql.sql
  - mysql -u root -e 'GRANT ALL PRIVILEGES ON autowp_image_test.* TO autowp_test@localhost IDENTIFIED BY "test";'
  - psql -c 'create database autowp_image_test;' -U postgres
  - psql --set ON_ERROR_STOP=on -U postgres autowp_image_test < test/_files/dump.pgsql.sql
script: 
  - composer cs-check
  - composer phpmd
  - PDODRIVER=pgsql ./vendor/bin/phpunit
  - PDODRIVER=mysql ./vendor/bin/phpunit --log-junit test/logs/junit.xml --coverage-clover ./test/logs/clover.xml
  - sonar-scanner || travis_terminate 1;

after_script:
  - ./vendor/bin/coveralls -v
  - ./vendor/bin/test-reporter -v --coverage-report=./logs/clover.xml
